name: EthriaPlotAddon
version: 1.1
main: de.leahcimkrob.ethriaPlotAddon.EthriaPlotAddon
api-version: '1.21'
description: Plugin zum Zählen von Entities auf Plots
author: leahcimkrob
website: https://github.com/leahcimkrob/EthriaPlotAddon

commands:
  plotcount:
    description: Zählt Entities auf einem Plot
    usage: /plotcount <entitytype|all|help|reload>
    permission: ethriaplotaddon.count.use

depend:
  - PlotSquared

permissions:
  # === ADMIN BERECHTIGUNGEN ===
  ethriaplotaddon.count.admin:
    description: Vollzugriff - darf alles auf jedem Plot zählen
    default: op
    children:
      ethriaplotaddon.count.use: true
      ethriaplotaddon.count.group.*: true
      ethriaplotaddon.count.entity.*: true
      ethriaplotaddon.count.own: true
      ethriaplotaddon.count.other: true
      ethriaplotaddon.count.reload: true

  # === BASIS BERECHTIGUNGEN ===
  ethriaplotaddon.count.use:
    description: Basis-Berechtigung um das Plugin zu verwenden
    default: false

  ethriaplotaddon.count.reload:
    description: Darf die Plugin-Konfiguration neu laden
    default: op

  # === PLOT-ZUGRIFF ===
  ethriaplotaddon.count.own:
    description: Darf auf eigenen, getrusted oder added Plots zählen (nur wenn Owner online)
    default: false

  ethriaplotaddon.count.other:
    description: Darf auch auf fremden Plots zählen
    default: op

  # === GRUPPEN-BERECHTIGUNGEN ===
  ethriaplotaddon-count.group.*:
    description: Darf alle Entity-Gruppen zählen
    default: op
    children:
      ethriaplotaddon.count.group.animals: true
      ethriaplotaddon.count.group.mobs: true
      ethriaplotaddon.count.group.entities: true
      ethriaplotaddon.count.group.vehicles: true
      ethriaplotaddon.count.group.items: true
      ethriaplotaddon.count.group.projectiles: true

  ethriaplotaddon.count.group.animals:
    description: Darf Tiere zählen (Kuh, Schaf, etc.)
    default: false

  ethriaplotaddon.count.group.mobs:
    description: Darf Monster zählen (Zombie, Skelett, etc.)
    default: false

  ethriaplotaddon.count.group.entities:
    description: Darf Entities zählen (Rüstungsständer, Itemframes, etc.)
    default: false

  ethriaplotaddon.count.group.vehicles:
    description: Darf Fahrzeuge zählen (Loren, Boote, etc.)
    default: false

  ethriaplotaddon.count.group.items:
    description: Darf Items zählen (Gegenstände, Erfahrungskugeln)
    default: false

  ethriaplotaddon.count.group.projectiles:
    description: Darf Projektile zählen (Pfeile, Feuerbälle, etc.)
    default: false

  # === EINZELNE ENTITIES ===
  ethriaplotaddon.count.entity.*:
    description: Darf alle Entities zählen
    default: op

  # Beispiele für spezifische Entity-Berechtigungen:
  ethriaplotaddon.count.entity.sheep:
    description: Darf Schafe zählen
    default: false

  ethriaplotaddon.count.entity.cow:
    description: Darf Kühe zählen
    default: false

  ethriaplotaddon.count.entity.armor_stand:
    description: Darf Rüstungsständer zählen
    default: false
